#!/usr/bin/env bash
bundle exec jekyll b -d docs
npx terser src/app.js -c toplevel=true -m toplevel=true --mangle-props -o assets/js/app.js
npx html-minifier --file-ext=html --input-dir docs/ --output-dir docs/ --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true
